name: setup
description: Setup dependencies

inputs:
  linters:
    description: "Install linters"
    required: false
    default: 'false'
  metal:
    description: "Install metal toolchain"
    required: false
    default: 'false'
  test_data:
    description: "Download test data"
    required: false
    default: 'false'
  nextest:
    description: "Install nextest"
    required: false
    default: 'false'
  target:
    description: "Additional Rust target to install"
    required: false
    default: ''

runs:
  using: composite
  steps:
    - uses: dtolnay/rust-toolchain@stable
      with:
        targets: ${{ inputs.target }}

    - uses: dtolnay/rust-toolchain@nightly
      with:
        components: ${{ inputs.linters == 'true' && 'rustfmt' || '' }}

    - if: inputs.target == 'wasm32-wasip1-threads'
      uses: bytecodealliance/actions/wasmtime/setup@v1

    - if: inputs.linters == 'true'
      run: |
        arch -arm64 brew install clang-format cargo-deny
      shell: bash

    - if: inputs.metal == 'true'
      run: |
        arch -arm64 brew install cmake
        xcodebuild -downloadComponent MetalToolchain
      shell: bash

    - if: inputs.nextest == 'true'
      uses: taiki-e/install-action@nextest

    - if: inputs.test_data == 'true'
      run: rm -rf ~/.local/share/uv/python
      shell: bash

    - if: inputs.test_data == 'true'
      uses: astral-sh/setup-uv@v7
      with:
        enable-cache: true
        python-version: "3.12"

    - if: inputs.test_data == 'true'
      run: |
        mkdir -p ~/.cache/ci-uzu/models
        ln -sf ~/.cache/ci-uzu/models workspace/models
        ./scripts/download_test_model.sh

        mkdir -p ~/.cache/ci-uzu/data/configs
        mkdir -p ~/.cache/ci-uzu/data/tokenizers
        ln -sf ~/.cache/ci-uzu/data/configs workspace/data/configs
        ln -sf ~/.cache/ci-uzu/data/tokenizers workspace/data/tokenizers
        cd ./tools/
        uv run export configs
        uv run export tokenizers
      shell: bash
