use crate::DataType;

#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub struct Specialization {
    pub block_rows: i32,
    pub block_cols: i32,
    pub block_depth: i32,
    pub warps_per_row: u64,
    pub warps_per_col: u64,
    pub swizzle_log2: i32,
    pub align_m: bool,
    pub align_n: bool,
    pub align_k: bool,
}

impl Specialization {
    pub fn precompile_configs(data_type: crate::DataType) -> &'static [Self] {
        match data_type {
            DataType::BF16 => &[
                Self {
                    block_rows: 64,
                    block_cols: 32,
                    block_depth: 32,
                    warps_per_row: 2,
                    warps_per_col: 2,
                    swizzle_log2: 0,
                    align_m: false,
                    align_n: true,
                    align_k: true,
                },
                Self {
                    block_rows: 64,
                    block_cols: 32,
                    block_depth: 32,
                    warps_per_row: 2,
                    warps_per_col: 2,
                    swizzle_log2: 0,
                    align_m: true,
                    align_n: true,
                    align_k: true,
                },
                Self {
                    block_rows: 64,
                    block_cols: 64,
                    block_depth: 16,
                    warps_per_row: 2,
                    warps_per_col: 2,
                    swizzle_log2: 0,
                    align_m: false,
                    align_n: true,
                    align_k: true,
                },
                Self {
                    block_rows: 64,
                    block_cols: 64,
                    block_depth: 16,
                    warps_per_row: 2,
                    warps_per_col: 2,
                    swizzle_log2: 0,
                    align_m: true,
                    align_n: false,
                    align_k: true,
                },
                Self {
                    block_rows: 64,
                    block_cols: 64,
                    block_depth: 16,
                    warps_per_row: 2,
                    warps_per_col: 2,
                    swizzle_log2: 0,
                    align_m: true,
                    align_n: true,
                    align_k: true,
                },
                Self {
                    block_rows: 64,
                    block_cols: 64,
                    block_depth: 16,
                    warps_per_row: 1,
                    warps_per_col: 2,
                    swizzle_log2: 0,
                    align_m: true,
                    align_n: true,
                    align_k: true,
                },
            ],
            DataType::F16 => &[
                Self {
                    block_rows: 64,
                    block_cols: 64,
                    block_depth: 16,
                    warps_per_row: 2,
                    warps_per_col: 2,
                    swizzle_log2: 0,
                    align_m: true,
                    align_n: true,
                    align_k: true,
                },
                Self {
                    block_rows: 64,
                    block_cols: 64,
                    block_depth: 16,
                    warps_per_row: 2,
                    warps_per_col: 2,
                    swizzle_log2: 0,
                    align_m: false,
                    align_n: true,
                    align_k: true,
                },
            ],
            DataType::F32 => &[
                Self {
                    block_rows: 32,
                    block_cols: 64,
                    block_depth: 16,
                    warps_per_row: 1,
                    warps_per_col: 2,
                    swizzle_log2: 0,
                    align_m: false,
                    align_n: true,
                    align_k: true,
                },
                Self {
                    block_rows: 32,
                    block_cols: 64,
                    block_depth: 16,
                    warps_per_row: 1,
                    warps_per_col: 2,
                    swizzle_log2: 0,
                    align_m: true,
                    align_n: true,
                    align_k: true,
                },
            ],
            _ => &[],
        }
    }
}
