load("@rules_cc//cc:defs.bzl", "cc_binary", "cc_library")

cc_library(
    name = "memory_counters",
    srcs = ["memory_counters.c"],
    hdrs = ["memory_counters.h"],
)

cc_binary(
    name = "engine-mldrift",
    srcs = [
        "bench.hpp",
        "common.cpp",
        "common.hpp",
        "engine.cpp",
        "engine.hpp",
        "main.cpp",
        "prompt_tokenizer.cpp",
        "prompt_tokenizer.hpp",
    ],
    deps = [
        ":memory_counters",
        "//ml_drift/samples/llm:llm_config",
        "//ml_drift/samples/llm:llm_runner_interface",
        "//ml_drift/samples/llm:llm_runner_metal_lib",
        "@com_google_absl//absl/flags:flag",
        "@com_google_absl//absl/flags:parse",
        "@com_google_absl//absl/status",
        "@glaze",
    ],
)
