/* automatically generated by rust-bindgen 0.72.1 */

#[repr(C)]
#[derive(Debug, Default, Copy, Clone)]
pub struct GEMMParams {
    pub M: ::core::ffi::c_int,
    pub N: ::core::ffi::c_int,
    pub K: ::core::ffi::c_int,
    pub lda: ::core::ffi::c_int,
    pub ldb: ::core::ffi::c_int,
    pub ldd: ::core::ffi::c_int,
    pub tiles_n: ::core::ffi::c_int,
    pub tiles_m: ::core::ffi::c_int,
    pub batch_stride_a: i64,
    pub batch_stride_b: i64,
    pub batch_stride_d: i64,
    pub swizzle_log: ::core::ffi::c_int,
    pub gemm_k_iterations_aligned: ::core::ffi::c_int,
    pub batch_ndim: ::core::ffi::c_int,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of GEMMParams"][::core::mem::size_of::<GEMMParams>() - 72usize];
    ["Alignment of GEMMParams"][::core::mem::align_of::<GEMMParams>() - 8usize];
    ["Offset of field: GEMMParams::M"]
        [::core::mem::offset_of!(GEMMParams, M) - 0usize];
    ["Offset of field: GEMMParams::N"]
        [::core::mem::offset_of!(GEMMParams, N) - 4usize];
    ["Offset of field: GEMMParams::K"]
        [::core::mem::offset_of!(GEMMParams, K) - 8usize];
    ["Offset of field: GEMMParams::lda"]
        [::core::mem::offset_of!(GEMMParams, lda) - 12usize];
    ["Offset of field: GEMMParams::ldb"]
        [::core::mem::offset_of!(GEMMParams, ldb) - 16usize];
    ["Offset of field: GEMMParams::ldd"]
        [::core::mem::offset_of!(GEMMParams, ldd) - 20usize];
    ["Offset of field: GEMMParams::tiles_n"]
        [::core::mem::offset_of!(GEMMParams, tiles_n) - 24usize];
    ["Offset of field: GEMMParams::tiles_m"]
        [::core::mem::offset_of!(GEMMParams, tiles_m) - 28usize];
    ["Offset of field: GEMMParams::batch_stride_a"]
        [::core::mem::offset_of!(GEMMParams, batch_stride_a) - 32usize];
    ["Offset of field: GEMMParams::batch_stride_b"]
        [::core::mem::offset_of!(GEMMParams, batch_stride_b) - 40usize];
    ["Offset of field: GEMMParams::batch_stride_d"]
        [::core::mem::offset_of!(GEMMParams, batch_stride_d) - 48usize];
    ["Offset of field: GEMMParams::swizzle_log"]
        [::core::mem::offset_of!(GEMMParams, swizzle_log) - 56usize];
    ["Offset of field: GEMMParams::gemm_k_iterations_aligned"][::core::mem::offset_of!(
        GEMMParams,
        gemm_k_iterations_aligned
    ) - 60usize];
    ["Offset of field: GEMMParams::batch_ndim"]
        [::core::mem::offset_of!(GEMMParams, batch_ndim) - 64usize];
};
#[repr(C)]
#[derive(Debug, Default, Copy, Clone)]
pub struct GEMMSpiltKParams {
    pub M: ::core::ffi::c_int,
    pub N: ::core::ffi::c_int,
    pub K: ::core::ffi::c_int,
    pub lda: ::core::ffi::c_int,
    pub ldb: ::core::ffi::c_int,
    pub ldc: ::core::ffi::c_int,
    pub tiles_n: ::core::ffi::c_int,
    pub tiles_m: ::core::ffi::c_int,
    pub split_k_partitions: ::core::ffi::c_int,
    pub split_k_partition_stride: ::core::ffi::c_int,
    pub split_k_partition_size: ::core::ffi::c_int,
    pub gemm_k_iterations_aligned: ::core::ffi::c_int,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of GEMMSpiltKParams"]
        [::core::mem::size_of::<GEMMSpiltKParams>() - 48usize];
    ["Alignment of GEMMSpiltKParams"]
        [::core::mem::align_of::<GEMMSpiltKParams>() - 4usize];
    ["Offset of field: GEMMSpiltKParams::M"]
        [::core::mem::offset_of!(GEMMSpiltKParams, M) - 0usize];
    ["Offset of field: GEMMSpiltKParams::N"]
        [::core::mem::offset_of!(GEMMSpiltKParams, N) - 4usize];
    ["Offset of field: GEMMSpiltKParams::K"]
        [::core::mem::offset_of!(GEMMSpiltKParams, K) - 8usize];
    ["Offset of field: GEMMSpiltKParams::lda"]
        [::core::mem::offset_of!(GEMMSpiltKParams, lda) - 12usize];
    ["Offset of field: GEMMSpiltKParams::ldb"]
        [::core::mem::offset_of!(GEMMSpiltKParams, ldb) - 16usize];
    ["Offset of field: GEMMSpiltKParams::ldc"]
        [::core::mem::offset_of!(GEMMSpiltKParams, ldc) - 20usize];
    ["Offset of field: GEMMSpiltKParams::tiles_n"]
        [::core::mem::offset_of!(GEMMSpiltKParams, tiles_n) - 24usize];
    ["Offset of field: GEMMSpiltKParams::tiles_m"]
        [::core::mem::offset_of!(GEMMSpiltKParams, tiles_m) - 28usize];
    ["Offset of field: GEMMSpiltKParams::split_k_partitions"][::core::mem::offset_of!(
        GEMMSpiltKParams,
        split_k_partitions
    ) - 32usize];
    ["Offset of field: GEMMSpiltKParams::split_k_partition_stride"][::core::mem::offset_of!(
        GEMMSpiltKParams,
        split_k_partition_stride
    )
        - 36usize];
    ["Offset of field: GEMMSpiltKParams::split_k_partition_size"][::core::mem::offset_of!(
        GEMMSpiltKParams,
        split_k_partition_size
    ) - 40usize];
    ["Offset of field: GEMMSpiltKParams::gemm_k_iterations_aligned"][::core::mem::offset_of!(
        GEMMSpiltKParams,
        gemm_k_iterations_aligned
    )
        - 44usize];
};
#[repr(C)]
#[derive(Debug, Default, Copy, Clone)]
pub struct GEMMAddMMParams {
    pub ldc: ::core::ffi::c_int,
    pub fdc: ::core::ffi::c_int,
    pub batch_stride_c: i64,
    pub alpha: f32,
    pub beta: f32,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of GEMMAddMMParams"]
        [::core::mem::size_of::<GEMMAddMMParams>() - 24usize];
    ["Alignment of GEMMAddMMParams"]
        [::core::mem::align_of::<GEMMAddMMParams>() - 8usize];
    ["Offset of field: GEMMAddMMParams::ldc"]
        [::core::mem::offset_of!(GEMMAddMMParams, ldc) - 0usize];
    ["Offset of field: GEMMAddMMParams::fdc"]
        [::core::mem::offset_of!(GEMMAddMMParams, fdc) - 4usize];
    ["Offset of field: GEMMAddMMParams::batch_stride_c"]
        [::core::mem::offset_of!(GEMMAddMMParams, batch_stride_c) - 8usize];
    ["Offset of field: GEMMAddMMParams::alpha"]
        [::core::mem::offset_of!(GEMMAddMMParams, alpha) - 16usize];
    ["Offset of field: GEMMAddMMParams::beta"]
        [::core::mem::offset_of!(GEMMAddMMParams, beta) - 20usize];
};
