/* automatically generated by rust-bindgen 0.72.1 */

#[doc = " Parameters for the main GEMM kernel.\n Layout: 8 x int32, 3 x int64, 2 x int32 = 64 bytes total"]
#[repr(C)]
#[derive(Debug, Default, Copy, Clone)]
pub struct GEMMParams {
    #[doc = " M dimension - batch/number of tokens (rows of A, rows of D)"]
    pub batch: ::core::ffi::c_int,
    #[doc = " N dimension - output_dim (cols of B, cols of D)"]
    pub output_dim: ::core::ffi::c_int,
    #[doc = " K dimension - input_dim/reduction dimension (cols of A, rows of B)"]
    pub input_dim: ::core::ffi::c_int,
    pub lda: ::core::ffi::c_int,
    pub ldb: ::core::ffi::c_int,
    pub ldd: ::core::ffi::c_int,
    pub tiles_n: ::core::ffi::c_int,
    pub tiles_m: ::core::ffi::c_int,
    pub batch_stride_a: i64,
    pub batch_stride_b: i64,
    pub batch_stride_d: i64,
    pub swizzle_log: ::core::ffi::c_int,
    pub gemm_k_iterations_aligned: ::core::ffi::c_int,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of GEMMParams"][::core::mem::size_of::<GEMMParams>() - 64usize];
    ["Alignment of GEMMParams"][::core::mem::align_of::<GEMMParams>() - 8usize];
    ["Offset of field: GEMMParams::batch"]
        [::core::mem::offset_of!(GEMMParams, batch) - 0usize];
    ["Offset of field: GEMMParams::output_dim"]
        [::core::mem::offset_of!(GEMMParams, output_dim) - 4usize];
    ["Offset of field: GEMMParams::input_dim"]
        [::core::mem::offset_of!(GEMMParams, input_dim) - 8usize];
    ["Offset of field: GEMMParams::lda"]
        [::core::mem::offset_of!(GEMMParams, lda) - 12usize];
    ["Offset of field: GEMMParams::ldb"]
        [::core::mem::offset_of!(GEMMParams, ldb) - 16usize];
    ["Offset of field: GEMMParams::ldd"]
        [::core::mem::offset_of!(GEMMParams, ldd) - 20usize];
    ["Offset of field: GEMMParams::tiles_n"]
        [::core::mem::offset_of!(GEMMParams, tiles_n) - 24usize];
    ["Offset of field: GEMMParams::tiles_m"]
        [::core::mem::offset_of!(GEMMParams, tiles_m) - 28usize];
    ["Offset of field: GEMMParams::batch_stride_a"]
        [::core::mem::offset_of!(GEMMParams, batch_stride_a) - 32usize];
    ["Offset of field: GEMMParams::batch_stride_b"]
        [::core::mem::offset_of!(GEMMParams, batch_stride_b) - 40usize];
    ["Offset of field: GEMMParams::batch_stride_d"]
        [::core::mem::offset_of!(GEMMParams, batch_stride_d) - 48usize];
    ["Offset of field: GEMMParams::swizzle_log"]
        [::core::mem::offset_of!(GEMMParams, swizzle_log) - 56usize];
    ["Offset of field: GEMMParams::gemm_k_iterations_aligned"][::core::mem::offset_of!(
        GEMMParams,
        gemm_k_iterations_aligned
    ) - 60usize];
};
#[doc = " Parameters for addmm (alpha * A @ B + beta * C) operations"]
#[repr(C)]
#[derive(Debug, Default, Copy, Clone)]
pub struct GEMMAddMMParams {
    pub ldc: ::core::ffi::c_int,
    pub fdc: ::core::ffi::c_int,
    pub batch_stride_c: i64,
    pub alpha: f32,
    pub beta: f32,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of GEMMAddMMParams"]
        [::core::mem::size_of::<GEMMAddMMParams>() - 24usize];
    ["Alignment of GEMMAddMMParams"]
        [::core::mem::align_of::<GEMMAddMMParams>() - 8usize];
    ["Offset of field: GEMMAddMMParams::ldc"]
        [::core::mem::offset_of!(GEMMAddMMParams, ldc) - 0usize];
    ["Offset of field: GEMMAddMMParams::fdc"]
        [::core::mem::offset_of!(GEMMAddMMParams, fdc) - 4usize];
    ["Offset of field: GEMMAddMMParams::batch_stride_c"]
        [::core::mem::offset_of!(GEMMAddMMParams, batch_stride_c) - 8usize];
    ["Offset of field: GEMMAddMMParams::alpha"]
        [::core::mem::offset_of!(GEMMAddMMParams, alpha) - 16usize];
    ["Offset of field: GEMMAddMMParams::beta"]
        [::core::mem::offset_of!(GEMMAddMMParams, beta) - 20usize];
};
