mod allocator;
mod array;
mod backend;
mod classifier_context;
mod command_buffer;
pub mod compilation_parameters;
mod context;
mod copy_encoder;
pub mod encodable_block;
pub mod error;
pub mod kernel;
mod language_model_generator_context;
pub mod metal_extensions;
pub use array::MetalArray;
pub use backend::Metal;
pub use classifier_context::ClassifierContext;
pub use context::{DeviceArchitecture, DeviceClass, DeviceGeneration, MTLContext};
pub use encodable_block::Decoder;
pub use error::MTLError;
pub use kernel::{KernelDataType, dsl::MetalKernels};
pub use language_model_generator_context::LanguageModelGeneratorContext;
pub use metal::prelude::*;
pub use metal_extensions::{ComputeEncoderSetValue, FunctionConstantValuesSetValue};

pub use crate::backends::common::kernel::kv_cache_update::KVCacheUpdate;
