mod allocator;
mod array;
mod backend;
mod classifier_context;
mod command_buffer;
mod context;
mod copy_encoder;
mod data_type;
pub mod encodable_block;
pub mod error;
pub mod kernel;
mod language_model_generator_context;
pub mod metal_extensions;

pub use array::MetalArray;
pub use backend::Metal;
pub use classifier_context::ClassifierContext;
pub use context::{DeviceArchitecture, DeviceClass, DeviceGeneration, MetalContext};
pub use encodable_block::Decoder;
pub use error::MetalError;
pub use kernel::dsl::MetalKernels;
pub use language_model_generator_context::LanguageModelGeneratorContext;
pub use metal_extensions::{ComputeEncoderSetValue, FunctionConstantValuesSetValue};
