// prettier-ignore
/* eslint-disable */
// @ts-nocheck
/* auto-generated by NAPI-RS */

const { createRequire } = require('node:module')
require = createRequire(__filename)

const { readFileSync } = require('node:fs')
let nativeBinding = null
const loadErrors = []

const isMusl = () => {
  let musl = false
  if (process.platform === 'linux') {
    musl = isMuslFromFilesystem()
    if (musl === null) {
      musl = isMuslFromReport()
    }
    if (musl === null) {
      musl = isMuslFromChildProcess()
    }
  }
  return musl
}

const isFileMusl = (f) => f.includes('libc.musl-') || f.includes('ld-musl-')

const isMuslFromFilesystem = () => {
  try {
    return readFileSync('/usr/bin/ldd', 'utf-8').includes('musl')
  } catch {
    return null
  }
}

const isMuslFromReport = () => {
  let report = null
  if (typeof process.report?.getReport === 'function') {
    process.report.excludeNetwork = true
    report = process.report.getReport()
  }
  if (!report) {
    return null
  }
  if (report.header && report.header.glibcVersionRuntime) {
    return false
  }
  if (Array.isArray(report.sharedObjects)) {
    if (report.sharedObjects.some(isFileMusl)) {
      return true
    }
  }
  return false
}

const isMuslFromChildProcess = () => {
  try {
    return require('child_process').execSync('ldd --version', { encoding: 'utf8' }).includes('musl')
  } catch (e) {
    // If we reach this case, we don't know if the system is musl or not, so is better to just fallback to false
    return false
  }
}

function requireNative() {
  if (process.env.NAPI_RS_NATIVE_LIBRARY_PATH) {
    try {
      nativeBinding = require(process.env.NAPI_RS_NATIVE_LIBRARY_PATH);
    } catch (err) {
      loadErrors.push(err)
    }
  } else if (process.platform === 'android') {
    if (process.arch === 'arm64') {
      try {
        return require('./uzu.android-arm64.node')
      } catch (e) {
        loadErrors.push(e)
      }
      try {
        const binding = require('@trymirai/uzu-android-arm64')
        const bindingPackageVersion = require('@trymirai/uzu-android-arm64/package.json').version
        if (bindingPackageVersion !== '0.4.4' && process.env.NAPI_RS_ENFORCE_VERSION_CHECK && process.env.NAPI_RS_ENFORCE_VERSION_CHECK !== '0') {
          throw new Error(`Native binding package version mismatch, expected 0.4.4 but got ${bindingPackageVersion}. You can reinstall dependencies to fix this issue.`)
        }
        return binding
      } catch (e) {
        loadErrors.push(e)
      }
    } else if (process.arch === 'arm') {
      try {
        return require('./uzu.android-arm-eabi.node')
      } catch (e) {
        loadErrors.push(e)
      }
      try {
        const binding = require('@trymirai/uzu-android-arm-eabi')
        const bindingPackageVersion = require('@trymirai/uzu-android-arm-eabi/package.json').version
        if (bindingPackageVersion !== '0.4.4' && process.env.NAPI_RS_ENFORCE_VERSION_CHECK && process.env.NAPI_RS_ENFORCE_VERSION_CHECK !== '0') {
          throw new Error(`Native binding package version mismatch, expected 0.4.4 but got ${bindingPackageVersion}. You can reinstall dependencies to fix this issue.`)
        }
        return binding
      } catch (e) {
        loadErrors.push(e)
      }
    } else {
      loadErrors.push(new Error(`Unsupported architecture on Android ${process.arch}`))
    }
  } else if (process.platform === 'win32') {
    if (process.arch === 'x64') {
      try {
        return require('./uzu.win32-x64-msvc.node')
      } catch (e) {
        loadErrors.push(e)
      }
      try {
        const binding = require('@trymirai/uzu-win32-x64-msvc')
        const bindingPackageVersion = require('@trymirai/uzu-win32-x64-msvc/package.json').version
        if (bindingPackageVersion !== '0.4.4' && process.env.NAPI_RS_ENFORCE_VERSION_CHECK && process.env.NAPI_RS_ENFORCE_VERSION_CHECK !== '0') {
          throw new Error(`Native binding package version mismatch, expected 0.4.4 but got ${bindingPackageVersion}. You can reinstall dependencies to fix this issue.`)
        }
        return binding
      } catch (e) {
        loadErrors.push(e)
      }
    } else if (process.arch === 'ia32') {
      try {
        return require('./uzu.win32-ia32-msvc.node')
      } catch (e) {
        loadErrors.push(e)
      }
      try {
        const binding = require('@trymirai/uzu-win32-ia32-msvc')
        const bindingPackageVersion = require('@trymirai/uzu-win32-ia32-msvc/package.json').version
        if (bindingPackageVersion !== '0.4.4' && process.env.NAPI_RS_ENFORCE_VERSION_CHECK && process.env.NAPI_RS_ENFORCE_VERSION_CHECK !== '0') {
          throw new Error(`Native binding package version mismatch, expected 0.4.4 but got ${bindingPackageVersion}. You can reinstall dependencies to fix this issue.`)
        }
        return binding
      } catch (e) {
        loadErrors.push(e)
      }
    } else if (process.arch === 'arm64') {
      try {
        return require('./uzu.win32-arm64-msvc.node')
      } catch (e) {
        loadErrors.push(e)
      }
      try {
        const binding = require('@trymirai/uzu-win32-arm64-msvc')
        const bindingPackageVersion = require('@trymirai/uzu-win32-arm64-msvc/package.json').version
        if (bindingPackageVersion !== '0.4.4' && process.env.NAPI_RS_ENFORCE_VERSION_CHECK && process.env.NAPI_RS_ENFORCE_VERSION_CHECK !== '0') {
          throw new Error(`Native binding package version mismatch, expected 0.4.4 but got ${bindingPackageVersion}. You can reinstall dependencies to fix this issue.`)
        }
        return binding
      } catch (e) {
        loadErrors.push(e)
      }
    } else {
      loadErrors.push(new Error(`Unsupported architecture on Windows: ${process.arch}`))
    }
  } else if (process.platform === 'darwin') {
    try {
      return require('./uzu.darwin-universal.node')
    } catch (e) {
      loadErrors.push(e)
    }
    try {
      const binding = require('@trymirai/uzu-darwin-universal')
      const bindingPackageVersion = require('@trymirai/uzu-darwin-universal/package.json').version
      if (bindingPackageVersion !== '0.4.4' && process.env.NAPI_RS_ENFORCE_VERSION_CHECK && process.env.NAPI_RS_ENFORCE_VERSION_CHECK !== '0') {
        throw new Error(`Native binding package version mismatch, expected 0.4.4 but got ${bindingPackageVersion}. You can reinstall dependencies to fix this issue.`)
      }
      return binding
    } catch (e) {
      loadErrors.push(e)
    }
    if (process.arch === 'x64') {
      try {
        return require('./uzu.darwin-x64.node')
      } catch (e) {
        loadErrors.push(e)
      }
      try {
        const binding = require('@trymirai/uzu-darwin-x64')
        const bindingPackageVersion = require('@trymirai/uzu-darwin-x64/package.json').version
        if (bindingPackageVersion !== '0.4.4' && process.env.NAPI_RS_ENFORCE_VERSION_CHECK && process.env.NAPI_RS_ENFORCE_VERSION_CHECK !== '0') {
          throw new Error(`Native binding package version mismatch, expected 0.4.4 but got ${bindingPackageVersion}. You can reinstall dependencies to fix this issue.`)
        }
        return binding
      } catch (e) {
        loadErrors.push(e)
      }
    } else if (process.arch === 'arm64') {
      try {
        return require('./uzu.darwin-arm64.node')
      } catch (e) {
        loadErrors.push(e)
      }
      try {
        const binding = require('@trymirai/uzu-darwin-arm64')
        const bindingPackageVersion = require('@trymirai/uzu-darwin-arm64/package.json').version
        if (bindingPackageVersion !== '0.4.4' && process.env.NAPI_RS_ENFORCE_VERSION_CHECK && process.env.NAPI_RS_ENFORCE_VERSION_CHECK !== '0') {
          throw new Error(`Native binding package version mismatch, expected 0.4.4 but got ${bindingPackageVersion}. You can reinstall dependencies to fix this issue.`)
        }
        return binding
      } catch (e) {
        loadErrors.push(e)
      }
    } else {
      loadErrors.push(new Error(`Unsupported architecture on macOS: ${process.arch}`))
    }
  } else if (process.platform === 'freebsd') {
    if (process.arch === 'x64') {
      try {
        return require('./uzu.freebsd-x64.node')
      } catch (e) {
        loadErrors.push(e)
      }
      try {
        const binding = require('@trymirai/uzu-freebsd-x64')
        const bindingPackageVersion = require('@trymirai/uzu-freebsd-x64/package.json').version
        if (bindingPackageVersion !== '0.4.4' && process.env.NAPI_RS_ENFORCE_VERSION_CHECK && process.env.NAPI_RS_ENFORCE_VERSION_CHECK !== '0') {
          throw new Error(`Native binding package version mismatch, expected 0.4.4 but got ${bindingPackageVersion}. You can reinstall dependencies to fix this issue.`)
        }
        return binding
      } catch (e) {
        loadErrors.push(e)
      }
    } else if (process.arch === 'arm64') {
      try {
        return require('./uzu.freebsd-arm64.node')
      } catch (e) {
        loadErrors.push(e)
      }
      try {
        const binding = require('@trymirai/uzu-freebsd-arm64')
        const bindingPackageVersion = require('@trymirai/uzu-freebsd-arm64/package.json').version
        if (bindingPackageVersion !== '0.4.4' && process.env.NAPI_RS_ENFORCE_VERSION_CHECK && process.env.NAPI_RS_ENFORCE_VERSION_CHECK !== '0') {
          throw new Error(`Native binding package version mismatch, expected 0.4.4 but got ${bindingPackageVersion}. You can reinstall dependencies to fix this issue.`)
        }
        return binding
      } catch (e) {
        loadErrors.push(e)
      }
    } else {
      loadErrors.push(new Error(`Unsupported architecture on FreeBSD: ${process.arch}`))
    }
  } else if (process.platform === 'linux') {
    if (process.arch === 'x64') {
      if (isMusl()) {
        try {
          return require('./uzu.linux-x64-musl.node')
        } catch (e) {
          loadErrors.push(e)
        }
        try {
          const binding = require('@trymirai/uzu-linux-x64-musl')
          const bindingPackageVersion = require('@trymirai/uzu-linux-x64-musl/package.json').version
          if (bindingPackageVersion !== '0.4.4' && process.env.NAPI_RS_ENFORCE_VERSION_CHECK && process.env.NAPI_RS_ENFORCE_VERSION_CHECK !== '0') {
            throw new Error(`Native binding package version mismatch, expected 0.4.4 but got ${bindingPackageVersion}. You can reinstall dependencies to fix this issue.`)
          }
          return binding
        } catch (e) {
          loadErrors.push(e)
        }
      } else {
        try {
          return require('./uzu.linux-x64-gnu.node')
        } catch (e) {
          loadErrors.push(e)
        }
        try {
          const binding = require('@trymirai/uzu-linux-x64-gnu')
          const bindingPackageVersion = require('@trymirai/uzu-linux-x64-gnu/package.json').version
          if (bindingPackageVersion !== '0.4.4' && process.env.NAPI_RS_ENFORCE_VERSION_CHECK && process.env.NAPI_RS_ENFORCE_VERSION_CHECK !== '0') {
            throw new Error(`Native binding package version mismatch, expected 0.4.4 but got ${bindingPackageVersion}. You can reinstall dependencies to fix this issue.`)
          }
          return binding
        } catch (e) {
          loadErrors.push(e)
        }
      }
    } else if (process.arch === 'arm64') {
      if (isMusl()) {
        try {
          return require('./uzu.linux-arm64-musl.node')
        } catch (e) {
          loadErrors.push(e)
        }
        try {
          const binding = require('@trymirai/uzu-linux-arm64-musl')
          const bindingPackageVersion = require('@trymirai/uzu-linux-arm64-musl/package.json').version
          if (bindingPackageVersion !== '0.4.4' && process.env.NAPI_RS_ENFORCE_VERSION_CHECK && process.env.NAPI_RS_ENFORCE_VERSION_CHECK !== '0') {
            throw new Error(`Native binding package version mismatch, expected 0.4.4 but got ${bindingPackageVersion}. You can reinstall dependencies to fix this issue.`)
          }
          return binding
        } catch (e) {
          loadErrors.push(e)
        }
      } else {
        try {
          return require('./uzu.linux-arm64-gnu.node')
        } catch (e) {
          loadErrors.push(e)
        }
        try {
          const binding = require('@trymirai/uzu-linux-arm64-gnu')
          const bindingPackageVersion = require('@trymirai/uzu-linux-arm64-gnu/package.json').version
          if (bindingPackageVersion !== '0.4.4' && process.env.NAPI_RS_ENFORCE_VERSION_CHECK && process.env.NAPI_RS_ENFORCE_VERSION_CHECK !== '0') {
            throw new Error(`Native binding package version mismatch, expected 0.4.4 but got ${bindingPackageVersion}. You can reinstall dependencies to fix this issue.`)
          }
          return binding
        } catch (e) {
          loadErrors.push(e)
        }
      }
    } else if (process.arch === 'arm') {
      if (isMusl()) {
        try {
          return require('./uzu.linux-arm-musleabihf.node')
        } catch (e) {
          loadErrors.push(e)
        }
        try {
          const binding = require('@trymirai/uzu-linux-arm-musleabihf')
          const bindingPackageVersion = require('@trymirai/uzu-linux-arm-musleabihf/package.json').version
          if (bindingPackageVersion !== '0.4.4' && process.env.NAPI_RS_ENFORCE_VERSION_CHECK && process.env.NAPI_RS_ENFORCE_VERSION_CHECK !== '0') {
            throw new Error(`Native binding package version mismatch, expected 0.4.4 but got ${bindingPackageVersion}. You can reinstall dependencies to fix this issue.`)
          }
          return binding
        } catch (e) {
          loadErrors.push(e)
        }
      } else {
        try {
          return require('./uzu.linux-arm-gnueabihf.node')
        } catch (e) {
          loadErrors.push(e)
        }
        try {
          const binding = require('@trymirai/uzu-linux-arm-gnueabihf')
          const bindingPackageVersion = require('@trymirai/uzu-linux-arm-gnueabihf/package.json').version
          if (bindingPackageVersion !== '0.4.4' && process.env.NAPI_RS_ENFORCE_VERSION_CHECK && process.env.NAPI_RS_ENFORCE_VERSION_CHECK !== '0') {
            throw new Error(`Native binding package version mismatch, expected 0.4.4 but got ${bindingPackageVersion}. You can reinstall dependencies to fix this issue.`)
          }
          return binding
        } catch (e) {
          loadErrors.push(e)
        }
      }
    } else if (process.arch === 'riscv64') {
      if (isMusl()) {
        try {
          return require('./uzu.linux-riscv64-musl.node')
        } catch (e) {
          loadErrors.push(e)
        }
        try {
          const binding = require('@trymirai/uzu-linux-riscv64-musl')
          const bindingPackageVersion = require('@trymirai/uzu-linux-riscv64-musl/package.json').version
          if (bindingPackageVersion !== '0.4.4' && process.env.NAPI_RS_ENFORCE_VERSION_CHECK && process.env.NAPI_RS_ENFORCE_VERSION_CHECK !== '0') {
            throw new Error(`Native binding package version mismatch, expected 0.4.4 but got ${bindingPackageVersion}. You can reinstall dependencies to fix this issue.`)
          }
          return binding
        } catch (e) {
          loadErrors.push(e)
        }
      } else {
        try {
          return require('./uzu.linux-riscv64-gnu.node')
        } catch (e) {
          loadErrors.push(e)
        }
        try {
          const binding = require('@trymirai/uzu-linux-riscv64-gnu')
          const bindingPackageVersion = require('@trymirai/uzu-linux-riscv64-gnu/package.json').version
          if (bindingPackageVersion !== '0.4.4' && process.env.NAPI_RS_ENFORCE_VERSION_CHECK && process.env.NAPI_RS_ENFORCE_VERSION_CHECK !== '0') {
            throw new Error(`Native binding package version mismatch, expected 0.4.4 but got ${bindingPackageVersion}. You can reinstall dependencies to fix this issue.`)
          }
          return binding
        } catch (e) {
          loadErrors.push(e)
        }
      }
    } else if (process.arch === 'ppc64') {
      try {
        return require('./uzu.linux-ppc64-gnu.node')
      } catch (e) {
        loadErrors.push(e)
      }
      try {
        const binding = require('@trymirai/uzu-linux-ppc64-gnu')
        const bindingPackageVersion = require('@trymirai/uzu-linux-ppc64-gnu/package.json').version
        if (bindingPackageVersion !== '0.4.4' && process.env.NAPI_RS_ENFORCE_VERSION_CHECK && process.env.NAPI_RS_ENFORCE_VERSION_CHECK !== '0') {
          throw new Error(`Native binding package version mismatch, expected 0.4.4 but got ${bindingPackageVersion}. You can reinstall dependencies to fix this issue.`)
        }
        return binding
      } catch (e) {
        loadErrors.push(e)
      }
    } else if (process.arch === 's390x') {
      try {
        return require('./uzu.linux-s390x-gnu.node')
      } catch (e) {
        loadErrors.push(e)
      }
      try {
        const binding = require('@trymirai/uzu-linux-s390x-gnu')
        const bindingPackageVersion = require('@trymirai/uzu-linux-s390x-gnu/package.json').version
        if (bindingPackageVersion !== '0.4.4' && process.env.NAPI_RS_ENFORCE_VERSION_CHECK && process.env.NAPI_RS_ENFORCE_VERSION_CHECK !== '0') {
          throw new Error(`Native binding package version mismatch, expected 0.4.4 but got ${bindingPackageVersion}. You can reinstall dependencies to fix this issue.`)
        }
        return binding
      } catch (e) {
        loadErrors.push(e)
      }
    } else {
      loadErrors.push(new Error(`Unsupported architecture on Linux: ${process.arch}`))
    }
  } else if (process.platform === 'openharmony') {
    if (process.arch === 'arm64') {
      try {
        return require('./uzu.openharmony-arm64.node')
      } catch (e) {
        loadErrors.push(e)
      }
      try {
        const binding = require('@trymirai/uzu-openharmony-arm64')
        const bindingPackageVersion = require('@trymirai/uzu-openharmony-arm64/package.json').version
        if (bindingPackageVersion !== '0.4.4' && process.env.NAPI_RS_ENFORCE_VERSION_CHECK && process.env.NAPI_RS_ENFORCE_VERSION_CHECK !== '0') {
          throw new Error(`Native binding package version mismatch, expected 0.4.4 but got ${bindingPackageVersion}. You can reinstall dependencies to fix this issue.`)
        }
        return binding
      } catch (e) {
        loadErrors.push(e)
      }
    } else if (process.arch === 'x64') {
      try {
        return require('./uzu.openharmony-x64.node')
      } catch (e) {
        loadErrors.push(e)
      }
      try {
        const binding = require('@trymirai/uzu-openharmony-x64')
        const bindingPackageVersion = require('@trymirai/uzu-openharmony-x64/package.json').version
        if (bindingPackageVersion !== '0.4.4' && process.env.NAPI_RS_ENFORCE_VERSION_CHECK && process.env.NAPI_RS_ENFORCE_VERSION_CHECK !== '0') {
          throw new Error(`Native binding package version mismatch, expected 0.4.4 but got ${bindingPackageVersion}. You can reinstall dependencies to fix this issue.`)
        }
        return binding
      } catch (e) {
        loadErrors.push(e)
      }
    } else if (process.arch === 'arm') {
      try {
        return require('./uzu.openharmony-arm.node')
      } catch (e) {
        loadErrors.push(e)
      }
      try {
        const binding = require('@trymirai/uzu-openharmony-arm')
        const bindingPackageVersion = require('@trymirai/uzu-openharmony-arm/package.json').version
        if (bindingPackageVersion !== '0.4.4' && process.env.NAPI_RS_ENFORCE_VERSION_CHECK && process.env.NAPI_RS_ENFORCE_VERSION_CHECK !== '0') {
          throw new Error(`Native binding package version mismatch, expected 0.4.4 but got ${bindingPackageVersion}. You can reinstall dependencies to fix this issue.`)
        }
        return binding
      } catch (e) {
        loadErrors.push(e)
      }
    } else {
      loadErrors.push(new Error(`Unsupported architecture on OpenHarmony: ${process.arch}`))
    }
  } else {
    loadErrors.push(new Error(`Unsupported OS: ${process.platform}, architecture: ${process.arch}`))
  }
}

nativeBinding = requireNative()

if (!nativeBinding || process.env.NAPI_RS_FORCE_WASI) {
  try {
    nativeBinding = require('./uzu.wasi.cjs')
  } catch (err) {
    if (process.env.NAPI_RS_FORCE_WASI) {
      loadErrors.push(err)
    }
  }
  if (!nativeBinding) {
    try {
      nativeBinding = require('@trymirai/uzu-wasm32-wasi')
    } catch (err) {
      if (process.env.NAPI_RS_FORCE_WASI) {
        loadErrors.push(err)
      }
    }
  }
}

if (!nativeBinding) {
  if (loadErrors.length > 0) {
    throw new Error(
      `Cannot find native binding. ` +
        `npm has a bug related to optional dependencies (https://github.com/npm/cli/issues/4828). ` +
        'Please try `npm i` again after removing both package-lock.json and node_modules directory.',
      { cause: loadErrors }
    )
  }
  throw new Error(`Failed to load native binding`)
}

module.exports = nativeBinding
module.exports.ChatSession = nativeBinding.ChatSession
module.exports.ChatSessionStream = nativeBinding.ChatSessionStream
module.exports.ChatSessionStreamChunkError = nativeBinding.ChatSessionStreamChunkError
module.exports.ChatSessionStreamChunkReplies = nativeBinding.ChatSessionStreamChunkReplies
module.exports.ClassificationSession = nativeBinding.ClassificationSession
module.exports.TextToSpeechSession = nativeBinding.TextToSpeechSession
module.exports.TextToSpeechSessionStream = nativeBinding.TextToSpeechSessionStream
module.exports.TextToSpeechSessionStreamChunkError = nativeBinding.TextToSpeechSessionStreamChunkError
module.exports.TextToSpeechSessionStreamChunkOutput = nativeBinding.TextToSpeechSessionStreamChunkOutput
module.exports.ChatSessionState = nativeBinding.ChatSessionState
module.exports.ClassificationSessionState = nativeBinding.ClassificationSessionState
module.exports.TextToSpeechSessionState = nativeBinding.TextToSpeechSessionState
module.exports.CancelToken = nativeBinding.CancelToken
module.exports.ChatConfig = nativeBinding.ChatConfig
module.exports.ChatContentBlockAudio = nativeBinding.ChatContentBlockAudio
module.exports.ChatContentBlockBuiltinTools = nativeBinding.ChatContentBlockBuiltinTools
module.exports.ChatContentBlockConversationStartDate = nativeBinding.ChatContentBlockConversationStartDate
module.exports.ChatContentBlockCustom = nativeBinding.ChatContentBlockCustom
module.exports.ChatContentBlockFile = nativeBinding.ChatContentBlockFile
module.exports.ChatContentBlockIdentity = nativeBinding.ChatContentBlockIdentity
module.exports.ChatContentBlockImage = nativeBinding.ChatContentBlockImage
module.exports.ChatContentBlockKnowledgeCutoff = nativeBinding.ChatContentBlockKnowledgeCutoff
module.exports.ChatContentBlockReasoning = nativeBinding.ChatContentBlockReasoning
module.exports.ChatContentBlockReasoningEffort = nativeBinding.ChatContentBlockReasoningEffort
module.exports.ChatContentBlockText = nativeBinding.ChatContentBlockText
module.exports.ChatContentBlockToolCall = nativeBinding.ChatContentBlockToolCall
module.exports.ChatContentBlockToolCallCandidate = nativeBinding.ChatContentBlockToolCallCandidate
module.exports.ChatContentBlockToolCallResult = nativeBinding.ChatContentBlockToolCallResult
module.exports.ChatContentBlockTools = nativeBinding.ChatContentBlockTools
module.exports.ChatContentBlockTranslation = nativeBinding.ChatContentBlockTranslation
module.exports.ChatContentBlockVideo = nativeBinding.ChatContentBlockVideo
module.exports.ChatMessage = nativeBinding.ChatMessage
module.exports.ChatModelCapabilities = nativeBinding.ChatModelCapabilities
module.exports.ChatReply = nativeBinding.ChatReply
module.exports.ChatReplyConfig = nativeBinding.ChatReplyConfig
module.exports.ChatReplyStats = nativeBinding.ChatReplyStats
module.exports.ChatRoleAssistant = nativeBinding.ChatRoleAssistant
module.exports.ChatRoleCustom = nativeBinding.ChatRoleCustom
module.exports.ChatRoleDeveloper = nativeBinding.ChatRoleDeveloper
module.exports.ChatRoleSystem = nativeBinding.ChatRoleSystem
module.exports.ChatRoleTool = nativeBinding.ChatRoleTool
module.exports.ChatRoleUser = nativeBinding.ChatRoleUser
module.exports.ChatSpeculationPresetClassification = nativeBinding.ChatSpeculationPresetClassification
module.exports.ChatSpeculationPresetGeneralChat = nativeBinding.ChatSpeculationPresetGeneralChat
module.exports.ChatSpeculationPresetSummarization = nativeBinding.ChatSpeculationPresetSummarization
module.exports.ClassificationLabel = nativeBinding.ClassificationLabel
module.exports.ClassificationMessage = nativeBinding.ClassificationMessage
module.exports.ClassificationOutput = nativeBinding.ClassificationOutput
module.exports.ClassificationStats = nativeBinding.ClassificationStats
module.exports.ContextLengthCustom = nativeBinding.ContextLengthCustom
module.exports.ContextLengthDefault = nativeBinding.ContextLengthDefault
module.exports.ContextLengthMaximal = nativeBinding.ContextLengthMaximal
module.exports.Feature = nativeBinding.Feature
module.exports.File = nativeBinding.File
module.exports.GrammarJsonAny = nativeBinding.GrammarJsonAny
module.exports.GrammarJsonSchema = nativeBinding.GrammarJsonSchema
module.exports.GrammarRegex = nativeBinding.GrammarRegex
module.exports.Hash = nativeBinding.Hash
module.exports.Image = nativeBinding.Image
module.exports.Metadata = nativeBinding.Metadata
module.exports.Model = nativeBinding.Model
module.exports.ModelAccessibilityLocal = nativeBinding.ModelAccessibilityLocal
module.exports.ModelAccessibilityRemote = nativeBinding.ModelAccessibilityRemote
module.exports.ModelBackend = nativeBinding.ModelBackend
module.exports.ModelFamily = nativeBinding.ModelFamily
module.exports.ModelProperties = nativeBinding.ModelProperties
module.exports.ModelQuantization = nativeBinding.ModelQuantization
module.exports.ModelReferenceHuggingFace = nativeBinding.ModelReferenceHuggingFace
module.exports.ModelReferenceLocal = nativeBinding.ModelReferenceLocal
module.exports.ModelReferenceMirai = nativeBinding.ModelReferenceMirai
module.exports.ModelRegistry = nativeBinding.ModelRegistry
module.exports.ModelSpecializationChat = nativeBinding.ModelSpecializationChat
module.exports.ModelSpecializationClassification = nativeBinding.ModelSpecializationClassification
module.exports.ModelSpecializationSpeculation = nativeBinding.ModelSpecializationSpeculation
module.exports.ModelSpecializationTextToSpeech = nativeBinding.ModelSpecializationTextToSpeech
module.exports.ModelSpecializationTranslation = nativeBinding.ModelSpecializationTranslation
module.exports.ModelVendor = nativeBinding.ModelVendor
module.exports.PcmBatch = nativeBinding.PcmBatch
module.exports.Repository = nativeBinding.Repository
module.exports.SamplingMethodGreedy = nativeBinding.SamplingMethodGreedy
module.exports.SamplingMethodStochastic = nativeBinding.SamplingMethodStochastic
module.exports.SamplingPolicyCustom = nativeBinding.SamplingPolicyCustom
module.exports.SamplingPolicyDefault = nativeBinding.SamplingPolicyDefault
module.exports.SamplingSeedCustom = nativeBinding.SamplingSeedCustom
module.exports.SamplingSeedDefault = nativeBinding.SamplingSeedDefault
module.exports.TextToSpeechOutput = nativeBinding.TextToSpeechOutput
module.exports.TextToSpeechStats = nativeBinding.TextToSpeechStats
module.exports.Token = nativeBinding.Token
module.exports.ToolCall = nativeBinding.ToolCall
module.exports.ToolDescriptionFunction = nativeBinding.ToolDescriptionFunction
module.exports.ToolFunction = nativeBinding.ToolFunction
module.exports.ToolNamespace = nativeBinding.ToolNamespace
module.exports.TranslationPayloadImage = nativeBinding.TranslationPayloadImage
module.exports.TranslationPayloadText = nativeBinding.TranslationPayloadText
module.exports.Value = nativeBinding.Value
module.exports.ChatContentBlockType = nativeBinding.ChatContentBlockType
module.exports.ChatReplyFinishReason = nativeBinding.ChatReplyFinishReason
module.exports.ClassificationRole = nativeBinding.ClassificationRole
module.exports.HashMethod = nativeBinding.HashMethod
module.exports.ImageFormat = nativeBinding.ImageFormat
module.exports.ImageTheme = nativeBinding.ImageTheme
module.exports.ReasoningEffort = nativeBinding.ReasoningEffort
module.exports.CliApplication = nativeBinding.CliApplication
module.exports.Device = nativeBinding.Device
module.exports.Downloader = nativeBinding.Downloader
module.exports.DownloaderStream = nativeBinding.DownloaderStream
module.exports.DownloaderStreamUpdate = nativeBinding.DownloaderStreamUpdate
module.exports.DownloadPhaseDownloaded = nativeBinding.DownloadPhaseDownloaded
module.exports.DownloadPhaseDownloading = nativeBinding.DownloadPhaseDownloading
module.exports.DownloadPhaseError = nativeBinding.DownloadPhaseError
module.exports.DownloadPhaseLocked = nativeBinding.DownloadPhaseLocked
module.exports.DownloadPhaseNotDownloaded = nativeBinding.DownloadPhaseNotDownloaded
module.exports.DownloadPhasePaused = nativeBinding.DownloadPhasePaused
module.exports.DownloadState = nativeBinding.DownloadState
module.exports.Engine = nativeBinding.Engine
module.exports.EngineCallback = nativeBinding.EngineCallback
module.exports.EngineConfig = nativeBinding.EngineConfig
module.exports.Player = nativeBinding.Player
module.exports.Settings = nativeBinding.Settings
module.exports.SettingKind = nativeBinding.SettingKind
