[env]
RUST_TEST_THREADS = "1"

[target.wasm32-wasip1-threads]
# threads=y         — wasmtime need this flag to use threads
# shared-memory=y   — wasmtime need this flag to use shared memory
# --dir /::/        — allow wasmtime to read current directory
runner = ["wasmtime", "-W", "threads=y,shared-memory=y", "-S", "threads=y", "--dir", "/::/", "--"]

# --max-memory      — default max memory = 1Gb
rustflags = ["-C", "link-arg=--max-memory=4294967296"]