[package]
name = "xgrammar-ffi-sys"
version = "0.1.0"
edition = "2021"
links = "xgrammar"
build = "build.rs"

[lib]
name = "xgrammar_ffi_sys"
crate-type = ["rlib"]

[dependencies]

[build-dependencies]
cc = "1.0"
cmake = "0.1"
