name: "Tests"

on:
  push:
    branches:
      - main
  pull_request:
    types: [ opened, reopened, ready_for_review, synchronize ]
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

permissions:
  contents: read

defaults:
  run:
    # For pipefail - https://docs.github.com/en/actions/reference/workflows-and-actions/workflow-syntax#exit-codes-and-error-action-preference
    shell: bash

jobs:
  linters:
    name: linters
    runs-on: macos-26

    steps:
      - uses: actions/checkout@v6
      - id: setup
        uses: ./.github/actions/setup
        with:
          linters: true

      - name: Check Rust formatting
        if: ${{ always() && steps.setup.outcome == 'success' }}
        run: cargo +nightly fmt --check

      - name: Check Metal formatting
        if: ${{ always() && steps.setup.outcome == 'success' }}
        run: ./scripts/clang-format.sh --check

      - name: Check that Cargo.lock is consistent with Cargo.toml
        if: ${{ always() && steps.setup.outcome == 'success' }}
        run: |
          cargo metadata --locked --format-version=1 > /dev/null
          git diff --exit-code -- Cargo.lock

      - name: Check with cargo-deny
        if: ${{ always() && steps.setup.outcome == 'success' }}
        run: cargo deny check

  tests:
    name: ${{ matrix.backend }} ${{ matrix.tracing && ' (tracing)' || '' }}
    runs-on: [ self-hosted, macos, mac, arm64 ]
    if: ${{ github.event_name != 'pull_request' || github.event.pull_request.draft == false }}

    strategy:
      matrix:
        backend: [ 'cpu', 'metal' ]
        tracing: [ false, true ]

    env:
      CARGO_ENCODED_RUSTFLAGS: "-Dwarnings"

    steps:
      - uses: actions/checkout@v6
      - uses: ./.github/actions/setup
        with:
          metal: ${{ matrix.backend == 'metal' }}
          test_model: true
          nextest: true

      - name: Build crates
        run: |
          cargo +stable build --no-default-features \
            --features grammar \
            ${{ matrix.backend != 'cpu' && format('--features {0}', matrix.backend) || '' }} \
            ${{ matrix.tracing && '--features tracing' || '' }} \

      - name: Build benches
        if: ${{ matrix.backend != 'cpu' && !matrix.tracing }}
        run: |
          cargo +nightly bench --no-run --no-default-features \
            --features grammar \
            ${{ matrix.backend != 'cpu' && format('--features {0}', matrix.backend) || '' }} \
            ${{ matrix.tracing && '--features tracing' || '' }} \

      - name: Run tests
        if: ${{ matrix.backend != 'cpu' && matrix.tracing }}
        run: |
          cargo +stable nextest run --profile=ci --no-default-features \
            --features grammar \
            ${{ format('--features {0}', matrix.backend) || '' }} \
            --features tracing

  completed:
    name: completed
    runs-on: ubuntu-latest
    needs: [ linters, tests ]
    if: ${{ always() }}

    steps:
      - run: |
          [ "${{ needs.linters.result }}" = success ]
          [ "${{ needs.tests.result }}" = success ]
