name: "Tests"

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

permissions:
  contents: read

defaults:
  run:
    # For pipefail - https://docs.github.com/en/actions/reference/workflows-and-actions/workflow-syntax#exit-codes-and-error-action-preference
    shell: bash

jobs:
  linters:
    name: linters
    runs-on: macos-26

    steps:
      - uses: actions/checkout@v6
      - id: setup
        uses: ./.github/actions/setup
        with:
          linters: true

      - name: Check Rust formatting
        if: ${{ always() && steps.setup.outcome == 'success' }}
        run: cargo +nightly fmt --check

      - name: Check Metal formatting
        if: ${{ always() && steps.setup.outcome == 'success' }}
        run: ./scripts/clang-format.sh --check

      - name: Check that Cargo.lock is consistent with Cargo.toml
        if: ${{ always() && steps.setup.outcome == 'success' }}
        run: |
          cargo metadata --locked --format-version=1 > /dev/null
          git diff --exit-code -- Cargo.lock

      - name: Check with cargo-deny
        if: ${{ always() && steps.setup.outcome == 'success' }}
        run: cargo deny check

  tests:
    name: ${{ matrix.backend }}
      ${{ matrix.tracing && ' (tracing)' || '' }}
      ${{ matrix.grammar && ' (grammar)' || '' }}
      ${{ matrix.target != '' && format(' ({0})', matrix.target) || '' }}
    runs-on: [ self-hosted, macos, mac, arm64 ]

    strategy:
      matrix:
        backend: [ 'cpu', 'metal' ]
        target: [ '' ]
        tracing: [ false, true ]
        include:
          - grammar: true
          - backend: 'cpu'
            target: 'wasm32-wasip1-threads'
            tracing: false
            grammar: false
        exclude:
          - backend: 'cpu'
            tracing: true

    env:
      CARGO_ENCODED_RUSTFLAGS: "-Dwarnings"
      FEATURE_FLAGS: >-
        ${{ matrix.target != '' && format('--target {0}', matrix.target) || '' }}
        ${{ matrix.backend != 'cpu' && format('--features {0}', matrix.backend) || '' }}
        ${{ matrix.grammar && '--features grammar' || '' }}
        ${{ matrix.tracing && '--features tracing' || '' }}

    steps:
      - uses: actions/checkout@v6
      - uses: ./.github/actions/setup
        with:
          metal: ${{ matrix.backend == 'metal' }}
          test_data: true
          nextest: true
          target: ${{ matrix.target }}

      - name: Build crates
        run: cargo +stable build --no-default-features $FEATURE_FLAGS ${{ matrix.target == 'wasm32-wasip1-threads' && '-p uzu' || '' }}

      - name: Build benches
        if: ${{ matrix.backend != 'cpu' && !matrix.tracing }}
        run: cargo +nightly bench --no-run --no-default-features $FEATURE_FLAGS

      - name: Run tests
        if: ${{ matrix.backend != 'cpu' && matrix.tracing && matrix.grammar || matrix.backend == 'cpu' && !matrix.tracing && !matrix.grammar && matrix.target == 'wasm32-wasip1-threads' }}
        run: |
          cargo +stable nextest run --profile=ci --no-default-features $FEATURE_FLAGS \
            ${{ matrix.target == 'wasm32-wasip1-threads' && '-p backend-uzu --lib --test kernel' || '' }}

  completed:
    name: completed
    runs-on: ubuntu-latest
    needs: [ linters, tests ]
    if: ${{ always() }}

    steps:
      - run: |
          [ "${{ needs.linters.result }}" = success ]
          [ "${{ needs.tests.result }}" = success ]
