/* automatically generated by rust-bindgen 0.72.1 */

#[doc = " Parameters for the Gemm attention kernel.\n\n All strides are in **elements**, not bytes.\n Q/K/V/O are treated as 3D tensors with strides for:\n - [0] batch\n - [1] head (or kv-head for K/V)\n - [2] sequence (row stride for [seq, head_dim])"]
#[repr(C)]
#[derive(Debug, Default, Copy, Clone)]
pub struct AttnParams {
    pub q_strides: [i64; 3usize],
    pub k_strides: [i64; 3usize],
    pub v_strides: [i64; 3usize],
    pub o_strides: [i64; 3usize],
    pub gqa_factor: ::core::ffi::c_int,
    pub scale: f32,
    pub q_len: ::core::ffi::c_int,
    pub k_len: ::core::ffi::c_int,
    pub q_off: ::core::ffi::c_int,
    pub nq_aligned: ::core::ffi::c_int,
    pub q_rem: ::core::ffi::c_int,
    pub nk: ::core::ffi::c_int,
    pub nk_aligned: ::core::ffi::c_int,
    pub k_rem: ::core::ffi::c_int,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of AttnParams"][::core::mem::size_of::<AttnParams>() - 136usize];
    ["Alignment of AttnParams"][::core::mem::align_of::<AttnParams>() - 8usize];
    ["Offset of field: AttnParams::q_strides"]
        [::core::mem::offset_of!(AttnParams, q_strides) - 0usize];
    ["Offset of field: AttnParams::k_strides"]
        [::core::mem::offset_of!(AttnParams, k_strides) - 24usize];
    ["Offset of field: AttnParams::v_strides"]
        [::core::mem::offset_of!(AttnParams, v_strides) - 48usize];
    ["Offset of field: AttnParams::o_strides"]
        [::core::mem::offset_of!(AttnParams, o_strides) - 72usize];
    ["Offset of field: AttnParams::gqa_factor"]
        [::core::mem::offset_of!(AttnParams, gqa_factor) - 96usize];
    ["Offset of field: AttnParams::scale"]
        [::core::mem::offset_of!(AttnParams, scale) - 100usize];
    ["Offset of field: AttnParams::q_len"]
        [::core::mem::offset_of!(AttnParams, q_len) - 104usize];
    ["Offset of field: AttnParams::k_len"]
        [::core::mem::offset_of!(AttnParams, k_len) - 108usize];
    ["Offset of field: AttnParams::q_off"]
        [::core::mem::offset_of!(AttnParams, q_off) - 112usize];
    ["Offset of field: AttnParams::nq_aligned"]
        [::core::mem::offset_of!(AttnParams, nq_aligned) - 116usize];
    ["Offset of field: AttnParams::q_rem"]
        [::core::mem::offset_of!(AttnParams, q_rem) - 120usize];
    ["Offset of field: AttnParams::nk"]
        [::core::mem::offset_of!(AttnParams, nk) - 124usize];
    ["Offset of field: AttnParams::nk_aligned"]
        [::core::mem::offset_of!(AttnParams, nk_aligned) - 128usize];
    ["Offset of field: AttnParams::k_rem"]
        [::core::mem::offset_of!(AttnParams, k_rem) - 132usize];
};
#[doc = " Parameters describing the additive attention mask.\n\n Mask is treated as a 2D matrix [qL, kL] with:\n - per-batch base offset (M_strides[0])\n - per-head base offset  (M_strides[1])\n - row stride in elements (M_strides[2])\n Column stride is assumed to be 1."]
#[repr(C)]
#[derive(Debug, Default, Copy, Clone)]
pub struct AttnMaskParams {
    pub m_strides: [i64; 3usize],
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of AttnMaskParams"]
        [::core::mem::size_of::<AttnMaskParams>() - 24usize];
    ["Alignment of AttnMaskParams"]
        [::core::mem::align_of::<AttnMaskParams>() - 8usize];
    ["Offset of field: AttnMaskParams::m_strides"]
        [::core::mem::offset_of!(AttnMaskParams, m_strides) - 0usize];
};
